spring:
  application:
    name: springDataMongodbExample
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: sampledb
      username: admin
      password: secret

eureka:
  client:    
    serviceUrl:
      defaultZone: http://eureka-server:8080/eureka

      
      
      
