spring:
  application:
    name: springDataMongodbExample
  data:
    mongodb:
      host: mongodb #172.17.0.7 
      port: 27017
      database: SampleMongodb
      username: admin
      password: secret

eureka:
  client:    
    serviceUrl:
      defaultZone: http://eureka-server:8080/eureka

      
      
      
